export const UPDATE_LEFT_MENU_STATUS = "UPDATE_LEFT_MENU_STATUS";
export const FETCH_USER = "FETCH_USER";
export const GET_BALANCE = "GET_BALANCE";
export const GET_USERS = `GET_USERS`;
export const GET_FOLLOWERS = `GET_FOLLOWERS`;
export const GET_FOLLOWING = `GET_FOLLOWING`;
export const GET_NETWORKS = `GET_NETWORKS`;
export const GET_FOLLOWED = `GET_FOLLOWED`;
export const UPDATE_FOLLOW = `UPDATE_FOLLOW`;
export const GET_NEWS_FEED = `GET_NEWS_FEED`;
export const ADD_ACCOUNT = `ADD_ACCOUNT`;
export const GET_NEWEST_USERS = `GET_NEWEST_USERS`;
export const SELECT_FEED = `SELECT_FEED`;
export const SAVE_ROUTE = `SAVE_ROUTE`;
export const GET_COMMENT_SUCCESS = `GET_COMMENT_SUCCESS`;
export const RESET_COMMENTS = `RESET_COMMENTS`;
export const UPDATE_COMMENT = `UPDATE_COMMENT`;
export const DELETE_COMENT = `DELETE_COMENT`;

export const CHANGE_MODE = `CHANGE_MODE`;
export const SIDEBAR_PROFILE_STATUS = `SIDEBAR_PROFILE_STATUS`;
export const GET_TOP_POPULAR = `GET_TOP_POPULAR`;
export const GET_MY_NEWS_FEED = `GET_MY_NEWS_FEED`;
export const UPDATE_LOCAL_FEED = `UPDATE_LOCAL_FEED`;
export const UPDATE_LOCAL_ACCOUNT_FEED = `UPDATE_LOCAL_ACCOUNT_FEED`;
export const SET_FEED_DETAIL_POPUP = `SET_FEED_DETAIL_POPUP`;
export const SET_FEED_DETAIL_IMAGE_INDEX = `SET_FEED_DETAIL_IMAGE_INDEX`;
export const UPDATE_FEED_DETAIL_FLAG = `UPDATE_FEED_DETAIL_FLAG`;

export const CHANGE_VOLUME_STATUS = `CHANGE_VOLUME_STATUS`;
export const TOGGLE_RANKING_FORM = `TOGGLE_RANKING_FORM`;

export const SAVE_PREVIEW_LINK = `SAVE_PREVIEW_LINK`;
export const SAVE_OFFSET = `SAVE_OFFSET`;
export const SAVE_CURRENT_ROUTE = `SAVE_CURRENT_ROUTE`;

export const UPDATE_MIN_HEIGHT = `UPDATE_MIN_HEIGHT`;
export const CHANGE_VERSION = `CHANGE_VERSION`;

export const ADD_WALLET_ADDRESS = `ADD_WALLET_ADDRESS`;
export const ADD_WALLET_SIGNATURE = `ADD_WALLET_SIGNATURE`;
export const ADD_METAMASK_SIGNER = `ADD_METAMASK_SIGNER`;
export const ADD_METAMASK_PROVIDER = `ADD_METAMASK_PROVIDER`;
export const ADD_CONFIG = `ADD_CONFIG`;

//setting reducer
export const CHANGE_LANGUAGE = `CHANGE_LANGUAGE`;
export const UPDATE_LOADING_STATUS = `UPDATE_LOADING_STATUS`;
export const UPDATE_REF = `UPDATE_REF`;
export const UPDATE_PARTNER_REF = `UPDATE_PARTNER_REF`;

//pre-sale
export const GET_PRE_SALE_ROUND_LIST = `GET_PRE_SALE_ROUND_LIST`;
export const GET_PRE_SALE_BALANCE = `GET_PRE_SALE_BALANCE`;

//user reducer
export const ADD_MY_ITEMS = `ADD_MY_ITEMS`;
export const UPDATE_WALLET_NAME = `UPDATE_WALLET_NAME`;
export const GET_TEMPLATES = `GET_TEMPLATES`;

//minting
export const GET_MINTING_BOX_LIST = `GET_MINTING_BOX_LIST`;
export const GET_USER_MINTING_BOX = `GET_USER_MINTING_BOX`;
export const GET_MINTING_COMBO_LIST = `GET_MINTING_COMBO_LIST`;

export const GET_ONCHAIN_BALANCE = "GET_ONCHAIN_BALANCE";
